#modelo da placa
BOARD_TAG = uno

# lista de bibliotecas utilizadas no sketch separadas por espaço
ARDUINO_LIBS =

#Caminho de instalação do Arduino-Makefile
include /usr/share/arduino/Arduino.mk

#Device para comunicação com a placa
ARDUINO_PORT = /dev/ttyACM0
