# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
#modelo da placa
BOARD_TAG = nano
BOARD_SUB = atmega328
ARDUINO_DIR = /usr/share/arduino/

# lista de bibliotecas utilizadas no sketch separadas por espaço
ARDUINO_LIBS =

#Caminho de instalação do Arduino-Makefile
include /usr/share/arduino/Arduino.mk

#Device para comunicação com a placa
ARDUINO_PORT = /dev/ttyUSB0

